name: gm_crypto
description: "flutter实现国密SM2、SM3、SM4算法"
version: 1.0.1
homepage: https://github.com/Chenshuai770/flutter_sm
repository: https://github.com/Chenshuai770/flutter_sm
issue_tracker: https://github.com/Chenshuai770/flutter_sm/issues

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

topics:
  - cryptography
  - encryption
  - sm2
  - sm3
  - sm4
